### ISSUE TITLE
Add django 2.1 to the available version options

### ISSUE THREAD

**Issue by joshua-s** [pydanny/cookiecutter-djangopackage#519]
* Date you used Cookiecutter DjangoPackage: 08/17/2018
* Cookiecutter version used, if known: 1.6.0
* Python version: 2.7
* Operating System: Mac OS Mojave (Beta)

### Description

I tried to enter Django 2.1 as a valid version for my package. The cookiecutter failed. Since Django 2.1 has now been released, this should not occur.

### What I Did

```sh
...
django_versions [1.11,2.0]: 1.11,2.0,2.1
...
ERROR:pre_gen_project:Invalid Django version "2.1".
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by francisbrito** [comment]
I might be wrong, but it seems to me this is caused by the fact that Python 2.7 is no longer supported in Django 2 (see [here](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django) and [here](https://www.twoscoopspress.com/pages/two-scoops-of-django-1-11-faq#what-about-django-1-9-2-0-etc)).

Either upgrading to Python 3.x or selecting Django version 1.11 should fix the problem.

**Comment by joshua-s** [comment]
Thanks for the update. Actually, this issue still occurs when I use Python 3. The line responsible is here: https://github.com/pydanny/cookiecutter-djangopackage/blob/master/cookiecutter.json#L11

**Comment by joshua-s** [comment]
I could add a PR, but not sure if this repo is still actively maintained.

**Comment by francisbrito** [comment]
Judging from the commit activity, it seems the project is slightly unmaintained, but personally I think it still works as a nice starting point for a Django Package.

Regarding the issue, I tried the following input:
```
full_name [Your full name here]: Francis Brito
email [you@example.com]: francis@xprs.co
github_username [yourname]: francisbrito
project_name [Django Package]: 
repo_name [dj-package]: 
app_name [dj_package]: 
app_config_name [DjPackageConfig]: 
project_short_description [Your project description goes here]: 
models [Comma-separated list of models]: 
django_versions [1.11,2.0]: 1.11,2.0,2.1
version [0.1.0]: 
create_example_project [N]: 
Select open_source_license:
1 - MIT
2 - BSD
3 - ISCL
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 (1, 2, 3, 4, 5) [1]: 1
```
With versions:
```
python --version
Python 3.6.6

cookiecutter --version
Cookiecutter 1.6.0 from <redacted> (Python 3.6)

pipenv --version
pipenv, version 2018.10.13
```

And the packaged seemed to work correctly (or at least no errors were thrown). Also tried with `django_versions [1.11,2.0]: 2.1` and worked too. 

There is [this commit](https://github.com/pydanny/cookiecutter-djangopackage/commit/5e2fefb0fc9586704bc511aa743653244b0cd2bb)  that was pushed some time after this issue was created. Could it be it fixed it?
